### ISSUE TITLE
Error: The file is not recoverable

### ISSUE THREAD

**Issue by dhruvguptadg** [stnolting/riscv_gcc_prebuilt#1]
I have downloaded the riscv_gcc_prebuilt using the "git clone" command. When i try to unpack any of the .tar.gz file in /data directory it shows me the following error:

"gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now"

I have gzip v1.10 installed. How do i unpack it to check the toolchain via make file.

Thanks,
Dhruv Gupta

**Comment by stnolting** [comment]
You can use `tar -xzf data/TOOLCHAIN.tar.gz -C TARGET_DIR/`. Replace *TOOLCHAIN* with the toolchain of choice and *TARGET_DIR* with your actual target directory.

I will add some more information on how to extract the archive to the README.md file.

**Comment by dhruvguptadg** [comment]
Same error is coming.
![VirtualBox_Ubuntu20 04_13_08_2020_21_08_12](https://user-images.githubusercontent.com/61554555/90176444-35337e00-dda9-11ea-90ea-a17a3efaf28f.png)

**Comment by stnolting** [comment]
This is strange...
Can you run `file ARCHIVE_NAME.tar.gz`?
Maybe its a problem with the file ending?!
I will investigate on this.

**Comment by dhruvguptadg** [comment]
it is showing "ASCII TEXT"

**Comment by stnolting** [comment]
Then there was a problem during the download.
If you are using a console: Use `git clone` to clone the complete repository or use `wget` to download the according toolchain archive.
Alternatively, you can directly download the file via your browser: [link](https://github.com/stnolting/riscv_gcc_prebuilt/raw/master/data/riscv32-unknown-elf.gcc-10.1.0.rv32i.ilp32.newlib.tar.gz) (will take a moment to start)

When you run the `file` command again, you should get "gzip compressed data".

**Comment by dhruvguptadg** [comment]
Same error.. i tried to download through all the three ways and it still shows the same error..!!

**Comment by stnolting** [comment]
You are right. There seems to be a file type error in this repository.
I've tried to fix that. Maybe you can try downloading (git clone) and uncompressing again.

**Comment by dhruvguptadg** [comment]
I tried it again as a super user but still the same error. If it is prebuilt can you just include directly the bin files in the repo?

**Comment by stnolting** [comment]
I'm still not sure where the problem is...
Anyway. Have you tried `wget`? That should work

`wget https://github.com/stnolting/riscv_gcc_prebuilt/raw/master/data/riscv32-unknown-elf.gcc-10.1.0.rv32i.ilp32.newlib.tar.gz`

**Comment by stnolting** [comment]
By the way, do you have [git lfs](https://git-lfs.github.com/) installed?

**Comment by stnolting** [comment]
Finally! You can download the whole repository as packed release (with intact archives):
https://github.com/stnolting/riscv_gcc_prebuilt/releases

**Comment by dhruvguptadg** [comment]
No i dont have git lfs installed? Is it required? Also by using wget it is properly downloaded and the toolchain check is OK. 

Thanks,
Dhruv Gupta

**Comment by stnolting** [comment]
I am not quite sure, but I think you need git lfs when cloning binary files...

Anyway, I'm happy that your toolchain works now! 👍
